name: qit_flutter
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  json_annotation: ^4.8.0

  freezed_annotation: ^2.2.0

  fluro: ^2.0.5

  get_it: ^7.2.0

  equatable: ^2.0.5

  dio: ^5.1.0

  easy_localization: ^3.0.1


  rxdart: ^0.27.7

  stack_trace: ^1.10.0

  shared_preferences: ^2.0.20

  flutter_lints: ^2.0.0

  xxtea: ^2.1.0

  flutter_svg: ^2.0.4
  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  custom_lint: ^0.3.2
  riverpod_lint: ^1.1.6

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
    - assets/logo/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Sukar
      fonts:
        - asset: assets/fonts/ar/Sukar-Regular.ttf
        - asset: assets/fonts/ar/Sukar-Bold.ttf
          weight: 700

    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/en/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/en/TitilliumWeb-Bold.ttf
          weight: 700

